import java.util.Scanner;
public class ExceptionDemo
{
static int a, b, c;
public static void main(String[] args)
{
System.out.println("Enter value for a and b :");
Scanner sc1 = new Scanner(System.in);
try
{
a = sc1.nextInt();
b = sc1.nextInt();
c = a / b; //divide by zero is not allowed in integer arithmetic
System.out.println("No Exception"); System.out.println("Value
of c =" + c);
}
catch (ArithmeticException ex1)
{
System.out.println(ex1);
}
} //close main() method
}
